# @file
# SConstruct build script for this module.
# This is template.
#
# @author Stephen Ord <stephen.ord@csiro.au>
#

from askapenv import env    # Always import this.

env.Append(CCFLAGS=['-O2', '-DASKAP_DEBUG', '-g'])

# create build object with library name
pkg = env.AskapPackage("linmos_mpi")

# add subpackages
pkg.AddSubPackage("linmosMPI")

# enable if this package should be built as a shared library
pkg.build_shared = False
pkg.build_static = True

# add functional tests
#env.SConscript("functests/SConscript")
env.AppendUnique(CCFLAGS=['-Wno-unused-local-typedef'])
# Run the build process.
pkg()
