#!/bin/bash
echo Removing old file
rm ./stress_test.db

echo Setting up the database
../apps/sms_tools.sh --create-schema --config ./sqlite.cfg --log-config ./sms.log_cfg

echo Generating $1 components
../apps/sms_tools.sh --gen-random-components $1 --config ./sqlite.cfg --log-config ./sms.log_cfg
