# @file
# SConstruct build script for this module.
# This is template.
#
# @author Daniel Collins <daniel.collins@csiro.au>
#

# Always import this
from askapenv import env
import os
import sys

if 'AIPSPATH' not in os.environ:
   os.environ['AIPSPATH']=os.environ['ASKAP_ROOT']+'/Code/Base/accessors/current'
env["ENV"]["AIPSPATH"] = os.environ['AIPSPATH']

#env.Append(CCFLAGS=['-O2', '-DASKAP_DEBUG', '-g'])

# create build object with library name
pkg = env.AskapPackage("skymodel")

# add subpackages
# pkg.AddSubPackages("subpackage_name")

# enable if this package should be built as a shared library
# pkg.build_shared = True

# add functional tests
env.SConscript("functests/SConscript")

# Run the build process.
pkg()
