/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "ContinuumComponent";

CREATE TABLE IF NOT EXISTS "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" INTEGER NOT NULL,
  "migration" INTEGER NOT NULL);

DELETE FROM "schema_version"
  WHERE "name" = '';

CREATE TABLE "ContinuumComponent" (
  "version" INTEGER NOT NULL,
  "continuum_component_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "polarisation_component_id" INTEGER NULL,
  "data_source_id" INTEGER NULL,
  CONSTRAINT "polarisation_component_id_fk"
    FOREIGN KEY ("polarisation_component_id")
    REFERENCES "Polarisation" ("polarisation_component_id")
    DEFERRABLE INITIALLY DEFERRED,
  CONSTRAINT "data_source_id_fk"
    FOREIGN KEY ("data_source_id")
    REFERENCES "DataSource" ("data_source_id")
    DEFERRABLE INITIALLY DEFERRED);

CREATE INDEX "ContinuumComponent_continuum_component_id_i"
  ON "ContinuumComponent" ("continuum_component_id");

INSERT OR IGNORE INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, 0);

