// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef CONTINUUM_COMPONENT_ODB_MYSQL_H
#define CONTINUUM_COMPONENT_ODB_MYSQL_H

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2040000 // 2.4.0
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
#include <odb/boost/date-time/mysql/posix-time-traits.hxx>
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "ContinuumComponent.h"

#include "DataSource-odb-mysql.h"
#include "Polarisation-odb-mysql.h"

#include "ContinuumComponent-odb.h"

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>
#include <odb/mysql/query-dynamic.hxx>

namespace odb
{
  // ContinuumComponent
  //
  template <typename A>
  struct pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >
  {
    // version
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::askap::cp::sms::datamodel::version_type,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    version_type_;

    static const version_type_ version;

    // continuum_component_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::askap::cp::sms::datamodel::id_type,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    continuum_component_id_type_;

    static const continuum_component_id_type_ continuum_component_id;

    // polarisation
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::askap::cp::sms::datamodel::id_type,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    polarisation_type_;

    static const polarisation_type_ polarisation;

    // data_source
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::askap::cp::sms::datamodel::id_type,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    data_source_type_;

    static const data_source_type_ data_source;
  };

#ifdef ODB_MYSQL_QUERY_COLUMNS_DEF

  template <typename A>
  const typename pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::version_type_
  pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::
  version (pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_common, typename A::common_traits >::version,
           A::table_name, "`version`", 0);

  template <typename A>
  const typename pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::continuum_component_id_type_
  pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::
  continuum_component_id (pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_common, typename A::common_traits >::continuum_component_id,
                          A::table_name, "`continuum_component_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::polarisation_type_
  pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::
  polarisation (pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_common, typename A::common_traits >::polarisation,
                A::table_name, "`polarisation_component_id`", 0);

  template <typename A>
  const typename pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::data_source_type_
  pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::
  data_source (pointer_query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_common, typename A::common_traits >::data_source,
               A::table_name, "`data_source_id`", 0);

#endif // ODB_MYSQL_QUERY_COLUMNS_DEF

  template <>
  class access::object_traits_impl< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >:
    public access::object_traits< ::askap::cp::sms::datamodel::ContinuumComponent >
  {
    public:
    typedef access::object_traits_impl< ::askap::cp::sms::datamodel::ContinuumComponent, id_common > common_traits;

    struct id_image_type
    {
      long long id_value;
      my_bool id_null;

      long long version_value;
      my_bool version_null;

      std::size_t version;
    };

    struct image_type
    {
      // version
      //
      long long version_value;
      my_bool version_null;

      // continuum_component_id
      //
      long long continuum_component_id_value;
      my_bool continuum_component_id_null;

      // polarisation
      //
      long long polarisation_value;
      my_bool polarisation_null;

      // data_source
      //
      long long data_source_value;
      my_bool data_source_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static version_type
    version (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&, bool bind_version = true);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&, const version_type* = 0);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 1UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char optimistic_erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static result<object_type>
    query (database&, const odb::query_base&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const odb::query_base&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  // ContinuumComponent
  //
  template <>
  struct alias_traits<
    ::askap::cp::sms::datamodel::Polarisation,
    id_mysql,
    access::object_traits_impl< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >::polarisation_tag>
  {
    typedef alias_traits<
      ::askap::cp::sms::datamodel::Polarisation,
      id_common,
      access::object_traits_impl< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >::polarisation_tag>
    common_traits;

    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::askap::cp::sms::datamodel::DataSource,
    id_mysql,
    access::object_traits_impl< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >::data_source_tag>
  {
    typedef alias_traits<
      ::askap::cp::sms::datamodel::DataSource,
      id_common,
      access::object_traits_impl< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >::data_source_tag>
    common_traits;

    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >
  {
    // polarisation
    //
    typedef
    odb::alias_traits<
      ::askap::cp::sms::datamodel::Polarisation,
      id_mysql,
      access::object_traits_impl< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >::polarisation_tag>
    polarisation_alias_;

    // data_source
    //
    typedef
    odb::alias_traits<
      ::askap::cp::sms::datamodel::DataSource,
      id_mysql,
      access::object_traits_impl< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >::data_source_tag>
    data_source_alias_;
  };

  template <typename A>
  struct query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >:
    query_columns_base< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql >
  {
    // version
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::askap::cp::sms::datamodel::version_type,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    version_type_;

    static const version_type_ version;

    // continuum_component_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::askap::cp::sms::datamodel::id_type,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    continuum_component_id_type_;

    static const continuum_component_id_type_ continuum_component_id;

    // polarisation
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::askap::cp::sms::datamodel::id_type,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    polarisation_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::askap::cp::sms::datamodel::Polarisation,
        id_mysql,
        polarisation_alias_ > >
    polarisation_pointer_type_;

    struct polarisation_type_: polarisation_pointer_type_, polarisation_column_type_
    {
      polarisation_type_ (odb::query_column< ::askap::cp::sms::datamodel::id_type >& qc,
                          const char* t, const char* c, const char* conv)
        : polarisation_column_type_ (qc, t, c, conv)
      {
      }
    };

    static const polarisation_type_ polarisation;

    // data_source
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::askap::cp::sms::datamodel::id_type,
        mysql::id_longlong >::query_type,
      mysql::id_longlong >
    data_source_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::askap::cp::sms::datamodel::DataSource,
        id_mysql,
        data_source_alias_ > >
    data_source_pointer_type_;

    struct data_source_type_: data_source_pointer_type_, data_source_column_type_
    {
      data_source_type_ (odb::query_column< ::askap::cp::sms::datamodel::id_type >& qc,
                         const char* t, const char* c, const char* conv)
        : data_source_column_type_ (qc, t, c, conv)
      {
      }
    };

    static const data_source_type_ data_source;
  };

#ifdef ODB_MYSQL_QUERY_COLUMNS_DEF

  template <typename A>
  const typename query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::version_type_
  query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::
  version (query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_common, typename A::common_traits >::version,
           A::table_name, "`version`", 0);

  template <typename A>
  const typename query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::continuum_component_id_type_
  query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::
  continuum_component_id (query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_common, typename A::common_traits >::continuum_component_id,
                          A::table_name, "`continuum_component_id`", 0);

  template <typename A>
  const typename query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::polarisation_type_
  query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::
  polarisation (query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_common, typename A::common_traits >::polarisation,
                A::table_name, "`polarisation_component_id`", 0);

  template <typename A>
  const typename query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::data_source_type_
  query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_mysql, A >::
  data_source (query_columns< ::askap::cp::sms::datamodel::ContinuumComponent, id_common, typename A::common_traits >::data_source,
               A::table_name, "`data_source_id`", 0);

#endif // ODB_MYSQL_QUERY_COLUMNS_DEF
}

#include "ContinuumComponent-odb-mysql.i"

#include <odb/post.hxx>

#endif // CONTINUUM_COMPONENT_ODB_MYSQL_H
