/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `ContinuumComponent`;

CREATE TABLE IF NOT EXISTS `schema_version` (
  `name` VARCHAR(255) NOT NULL PRIMARY KEY,
  `version` BIGINT UNSIGNED NOT NULL,
  `migration` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

DELETE FROM `schema_version`
  WHERE `name` = '';

CREATE TABLE `ContinuumComponent` (
  `version` BIGINT NOT NULL,
  `continuum_component_id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `polarisation_component_id` BIGINT NULL,
  `data_source_id` BIGINT NULL)
 ENGINE=InnoDB;

CREATE INDEX `continuum_component_id_i`
  ON `ContinuumComponent` (`continuum_component_id`);

/*
ALTER TABLE `ContinuumComponent`
  ADD CONSTRAINT `ContinuumComponent_polarisation_component_id_fk`
    FOREIGN KEY (`polarisation_component_id`)
    REFERENCES `Polarisation` (`polarisation_component_id`),
  ADD CONSTRAINT `ContinuumComponent_data_source_id_fk`
    FOREIGN KEY (`data_source_id`)
    REFERENCES `DataSource` (`data_source_id`)
*/

INSERT IGNORE INTO `schema_version` (
  `name`, `version`, `migration`)
  VALUES ('', 1, 0);

