# @file
# SConstruct build script for this module.
#

# Always import this
from askapenv import env

# create build object with library name
pkg = env.AskapPackage("daliuge_pipeline")

pkg.AddSubPackage("factory")
pkg.AddSubPackage("interface")

env.Append(CCFLAGS=['-O3'])

# run the build process
pkg()
